fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.17.1"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "2.4.0"
    epel:
      repo: "https://github.com/stahnma/puppet-module-epel"
      ref: "1.2.2"
  symlinks:
    varnish: "#{source_dir}"
