---
sudo: false
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
    - rvm: 2.1.9
      env: PUPPET_VERSION="~> 4.7" CHECK=test
    - rvm: 2.1.9
      env: PUPPET_VERSION="~> 4.8" CHECK=test
    - rvm: 2.1.9
      env: PUPPET_VERSION="~> 4.9" CHECK=test
